language: java

before_install:
 - chmod +x gradlew

addons:
  sonarqube:
    token:
      secure: SONAR_TOKEN # encrypted value of your token

jdk:
 - oraclejdk8

script:
 - "./gradlew clean build jacocoTestReport"
 - sonar-scanner